name: monerod
description: monerod in Dart.  A command-line interface.
version: 0.0.1-dev.1
repository: https://github.com/ManyMath/monerod-dart

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  native_toolchain_rust: ^0.1.0-dev.7
  native_assets_cli: ^0.7.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
